name: ci-cd

on:
  push:
    branches:
      - main


jobs:
  laravel-build-test:
    runs-on: ubuntu-latest
    container: composer

    steps:
      - uses: actions/checkout@v2

      - name: Install Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      - name: Create Environment file
        run: cp .env.example .env
      
      - name: Generate key
        run: php artisan key:generate
      
      - name: Execute tests (Unit and Feature tests) via PHPUnit
        run: vendor/bin/phpunit

      - name: Checkout 
        uses: actions/checkout@v2
  
  docker-build-push:
    runs-on: ubuntu-latest
    
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Build and push
        uses: docker/build-push-action@v2
        env:
          IMAGE_NAME: sary-app-laravel
          IMAGE_TAG: latest
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/$IMAGE_NAME:$IMAGE_TAG 