name: ci-cd

on:
  push:
    branches:
      - main


jobs:
  laravel-build-test:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout 
        uses: actions/checkout@v2

      - name: Install dependencies
        uses: php-actions/composer@v6
        with:
          php_version: "8.0"
          version: 2

      - name: Create Environment file
        run: cp .env.example .env
      
      - name: Generate key
        run: php artisan key:generate
      
      - name: Execute tests (Unit and Feature tests) via PHPUnit
        run: php artisan test
        env:
          DB_CONNECTION: 'sqlite'
          DB_DATABASE: ':memory:'

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      
      - name: check files
        run: ls
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/sary-app-laravel:latest 
